---
- name: Déployer BookListMVC localement avec ASPNETCORE_ENVIRONMENT=Development
  hosts: localhost
  vars_files:
    - vars.yaml
  tasks:

    - name: Restaurer les packages NuGet
      win_command: dotnet restore {{ dotnet_project }}
      args:
        chdir: "{{ dotnet_project }}"

    - name: Compiler et publier le projet
      win_command: dotnet publish {{ dotnet_project }} -c Release -o {{ publish_output }}
      args:
        chdir: "{{ dotnet_project }}"

    - name: Lancer l'application avec dotnet et variable ASPNETCORE_ENVIRONMENT
      win_shell: |
        $env:ASPNETCORE_ENVIRONMENT="Development"
        Start-Process -FilePath "dotnet" -ArgumentList "{{ publish_output }}\\BookListMVC.dll" -WindowStyle Hidden


